### ISSUE TITLE
Missing PID and Motor libraries

### ISSUE THREAD

**Issue by andrewferguson** [sebgiles/arduino-nxtservo#2]
This library references three other libraries:
- Motor.h
- PID.h
- Encoder.h

The readme helpfully points to the location of the [Encoder.h library](https://www.pjrc.com/teensy/td_libs_Encoder.html), however the motor and PID libraries used are not mentioned. There are quite a few motor and PID libraries available, but after searching for a couple of hours I'm not able to find ones that match the functions used in the code.

I'd really appreciate a pointer to the locations of these libraries! (As an incentive, I promise to write some examples and submit them via pull-request if I get this to work).

This looks to be a really good library and I'd love to use it, but without the necessary libraries I am not able to get it to compile.

**Comment by sebgiles** [comment]
Hi thanks for your interest in my project, the libraries are the ones I wrote myself, they are also available as repos on my account. Is is not very sophisticated and you might have to tune the PIDs again yourself. I did this year ago mostly as a way to get into Arduino, C++, OOP, Git, Controls and Electronics so I invite you to make changes as that way you will learn the most. 
https://github.com/sebgiles/PID
https://github.com/sebgiles/Motor

**Comment by sebgiles** [comment]
If you want to help you could add them as git submodules and make a PR :)

**Comment by sebgiles** [comment]
or edit the readme

**Comment by andrewferguson** [comment]
Many thanks for your help - and the very prompt reply. I've now got it to compile successfully.

However I haven't yet got it to work. To be honest, I've never come across PID controllers before, so am not really sure what I need to do in terms of setup. This is the code I'm trying:
    
    #include "NXTServo.h"
    
    const int NXT_WHITE_PIN = 5;
    const int NXT_BLACK_PIN = 6;
    const int NXT_YELLOW_PIN = 2;
    const int NXT_BLUE_PIN = 3;
    
    NXTServo nn = NXTServo(NXT_WHITE_PIN, NXT_BLACK_PIN, NXT_YELLOW_PIN, NXT_BLUE_PIN);
    
    void setup() {
      nn.turnAt(30);
    }
    
    void loop() {
      nn.update();
    }

(My actual end goal is to use the `NXTServo::goTo` method to turn to specific angles, but I thought it might be easier to test with the `turnAt` method).

I'm _pretty_ sure I've got the wiring correct. I've managed to get your `Motor` library working with the following code:

    #include "Motor.h"
    
    void setup() {
      Motor mm = Motor(5, 6, 9);
      mm.turn(0.5);
    }
    
    void loop() {}

From the _it works with the Motor library_ setup, I've connected the NXT red wire to ground, the yellow wire to pin 2, and the yellow wire to pin 3. I used a 10k and a 1k resistor to form a voltage divider across the 5v supply to get the ~4.5v necessary for the optical encoder (this ~4.5v is connected to the green wire).

When I upload the sketch, the LED on pin 13 gradually increases brightness from zero. I only thought to mention this as it's not my code doing that, so this may(?) be useful for debugging?

Thanks again for your help so far, and apologies for turning this issue into _help the n00b_ .

**Comment by sebgiles** [comment]
I don’t think there is anything controlling the LED. I don’t remember the wiring but please be sure it is correct. Also I just saw that the library has all PID parameters set to 0 so you will have to tune it. There are plenty of resources that explain the system if you want to try it. I’d say it’s quite fun and feels like magic. I recommend Brian Douglas on YouTube for an explanation.

If you just want something that works out of the box than maybe you should be looking somewhere else...

Sebastian

**Comment by andrewferguson** [comment]
Many thanks for your help. My issue was that I wasn't tuning the PID prior to moving the motor. I'd also configured the pullup resistors for the inputs incorrectly (by default I think it expects you to have external pullup resistors, but configuring it to use internal ones was straightforward).

Unfortunately I haven't had much success tuning the PID. It either overshoots completely, then gets stuck oscillating back and forth over the desired angle (when the value is too large), or it doesn't move at all (when the value is too small). I don't suppose you have kept your code with the tuning values that worked for you (just as a starting point)?

**Comment by sebgiles** [comment]
This code is over 5 years old, I no longer have access to the hardware so cannot provide them myself. I don't even have tuning parameters saved anywhere. But it is possible to make it work quite nicely after tuning.
